version: "3.3"
services:
    db_1:
      image: postgres:13-alpine
      ports:
        - "5436:5432"
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=tortoise_db
      restart: always

    db_2:
      image: postgres:13-alpine
      ports:
        - "5437:5432"
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=sqlalchemy_db
      restart: always



