"""Init

Revision ID: 9b04a22b39d6
Revises: 
Create Date: 2023-03-29 13:01:07.604503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b04a22b39d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sac_int', sa.Integer(), nullable=True),
    sa.Column('sac_str', sa.String(), nullable=True),
    sa.Column('sac_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbc_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbc_int', sa.Integer(), nullable=True),
    sa.Column('sbc_fk_sa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sbc_fk_sa'], ['a.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('da',
    sa.Column('sc_fk_sa', sa.Integer(), nullable=False),
    sa.Column('sc_fk_sd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sc_fk_sa'], ['a.id'], ),
    sa.ForeignKeyConstraint(['sc_fk_sd'], ['d.id'], ),
    sa.PrimaryKeyConstraint('sc_fk_sa', 'sc_fk_sd')
    )
    op.create_table('c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbc_str', sa.String(), nullable=True),
    sa.Column('sbc_fk_sb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sbc_fk_sb'], ['b.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('c')
    op.drop_table('da')
    op.drop_table('b')
    op.drop_table('d')
    op.drop_table('a')
    # ### end Alembic commands ###
